HW1 basic requirements
EasySocHacks/RecSys pull request #1
Opened 2022-11-20 17:25 UTC by alexanderlvarfolomeev

2022-11-20 20:37 UTC, EasySocHacks requested changes
See comments

2022-11-20 20:37 UTC, EasySocHacks commented on service/api/auth.py
> +from fastapi import HTTPException, Security
Думаю стоит вынести из api в какой-нибудь helper или utils (комментарий ко всему файлу)

2022-11-20 20:37 UTC, EasySocHacks commented on service/api/views.py
> +    },
ты протестил на pre-prod'е, что `.../docs` нормально отображает документацию на каждую ошибку?
если нет, запусти докер контейнер на другом порту (препрод) и протетси плз, а то там с этим свагером какие-то проблемы были на паре помню

2022-11-20 20:37 UTC, EasySocHacks commented on service/api/exceptions.py
> +        error_loc: tp.Optional[tp.Sequence[str]] = None,
давай для typing условимся импортить отдельные классы?
по типу `optional[Sequence[str]]`?

Мне кажется так будет приятнее выглядить.
Вопрос к другим ревьювером: вам как такой подход?

2022-11-20 20:37 UTC, EasySocHacks commented on service/api/views.py
> +    },
Предлагаю запустить `pre-prod` на порту `8081`.
Справишься? Запустишь?

2022-11-20 20:37 UTC, EasySocHacks commented on service/rec_models.py
> +import typing as tp
Аналогично, давай без `as`
просто использовать `List` и т. п.
Все равно нигде такое вроде больше не встретится, а выглядит приятнее

2022-11-20 20:37 UTC, EasySocHacks commented on service/rec_models.py
> +class TestModel(BaseRecModel):
Давай создадим отдельный файл для `base` модели, и отдельный доя каждой реализации?

2022-11-20 20:37 UTC, EasySocHacks commented on service/rec_models.py
> +class BaseRecModel:
`base` интерфейс стоит унаследовать от `abc.ABC`

2022-11-20 20:37 UTC, EasySocHacks commented on service/rec_models.py
> +modelByName = {
А это вообще стоит вынести в какой-нибудь конфиг и подгружать при старте приложения
N.B. стоит завести мб отдельную ветку для загрузки конфигов, но пока что можно просто через `pandas` или типа того грузить

2022-11-20 20:37 UTC, EasySocHacks commented on service/settings.py
> +    token: str = "Strong_TOKEN"
Надо токен хранить в будущем в конфиг файле, коорый будет в гитигноре
Пока вроде не критично, но надо будет сделать

2022-11-20 20:37 UTC, EasySocHacks commented on tests/api/test_views.py
> +    assert response.json()["errors"][0]["error_key"] == "http_exception"
Не очень понял информативность и как следствие нужду этого `assert`
Мы проверяем на `http_exception`, не очень понятно, что он внутри себя содержит
Может стоит что-то более информативное проверять/отдавать?

2022-11-20 20:37 UTC, EasySocHacks commented on tests/api/test_views.py
> +    assert response.json()["errors"][0]["error_key"] == "http_exception"
Опять не очень информативно

2022-11-20 20:37 UTC, EasySocHacks commented on tests/api/test_views.py
> +    assert response.json()["errors"][0]["error_key"] == "model_not_found"
Надо подумать, что делать с этой строчкой
У меня пока нет готового решения
Надо обговорить...

2022-11-23 14:32 UTC, EasySocHacks approved these changes

2022-11-23 14:39 UTC, ReachPeach reviewed
ˋ( ° ▽、° )

2022-11-23 14:47 UTC, merged